In [2]:
import os
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.cluster import DBSCAN
from sklearn.metrics import silhouette_score
from collections import Counter

In [5]:
# ── 1. Load data ──────────────────────────────────────────────
csv_path = 'synthetic_logs.csv'
df = pd.read_csv(csv_path)

print(f"Loaded {len(df)} log messages")
print(f"Columns: {list(df.columns)}")
print(f"Sources: {df['source'].unique()}")
print()

Loaded 2410 log messages
Columns: ['timestamp', 'source', 'log_message', 'target_label', 'complexity']
Sources: ['ModernCRM' 'AnalyticsEngine' 'ModernHR' 'BillingSystem' 'ThirdPartyAPI'
 'LegacyCRM']

In [6]:
# ── 2. Generate embeddings using SentenceTransformer ──────────
print("Loading SentenceTransformer model...")
model = SentenceTransformer('all-MiniLM-L6-v2')

log_messages = df['log_message'].astype(str).tolist()
print(f"Generating embeddings for {len(log_messages)} log messages...")
embeddings = model.encode(log_messages, show_progress_bar=True, batch_size=32)
print(f"Embedding shape: {embeddings.shape}")
print()

Loading SentenceTransformer model...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Generating embeddings for 2410 log messages...

Batches:   0%|          | 0/76 [00:00<?, ?it/s]

Embedding shape: (2410, 384)

In [12]:
# ── 3. Cluster with DBSCAN ───────────────────────────────────
print("Running DBSCAN clustering...")
dbscan = DBSCAN(eps=0.2, min_samples=1, metric='cosine')
cluster_labels = dbscan.fit_predict(embeddings)

df['cluster'] = cluster_labels
df.head()

Running DBSCAN clustering...

,timestamp,source,log_message,target_label,complexity,cluster
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0

In [13]:
df[df.cluster==1]

,timestamp,source,log_message,target_label,complexity,cluster
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1
10,8/9/2025 18:58,ModernCRM,Email server encountered a sending fault,Error,bert,1
217,1/22/2025 5:45,BillingSystem,Mail service encountered a delivery glitch,Error,bert,1
248,5/2/2025 23:04,ModernHR,Service disruption caused by email sending error,Critical Error,bert,1
265,3/30/2025 23:53,ModernCRM,Email system had a problem sending emails,Error,bert,1
361,11/19/2025 23:06,BillingSystem,Email service experienced a sending issue,Error,bert,1
450,10/27/2025 5:59,ThirdPartyAPI,Email delivery system encountered an error,Error,bert,1
477,12/2/2025 10:30,AnalyticsEngine,Email transmission error caused service impact,Critical Error,bert,1
570,11/7/2025 18:08,ThirdPartyAPI,Email service impacted by sending failure,Critical Error,bert,1
678,4/28/2025 15:13,AnalyticsEngine,Email delivery problem affected system,Critical Error,bert,1
695,6/30/2025 12:46,ThirdPartyAPI,Service outage due to email delivery problem,Critical Error,bert,1
816,7/9/2025 9:38,BillingSystem,Error in email delivery affected service,Critical Error,bert,1
926,2/17/2025 8:01,ModernCRM,Email service suffered a delivery failure,Error,bert,1
1011,2/9/2025 17:04,AnalyticsEngine,Error in email sending impacted service,Critical Error,bert,1
1018,2/16/2025 15:02,BillingSystem,Mail service impacted by delivery glitch,Critical Error,bert,1
1046,11/26/2025 22:54,AnalyticsEngine,Email service had a difficulty delivering mess...,Error,bert,1
1058,10/24/2025 5:37,AnalyticsEngine,Email system failed to deliver emails,Error,bert,1
1082,5/17/2025 11:20,ModernHR,Delivery failure impacted email services,Critical Error,bert,1
1151,6/17/2025 15:13,ThirdPartyAPI,Mail service was unable to send emails,Error,bert,1
1176,10/1/2025 12:27,AnalyticsEngine,Email provider faced a delivery challenge,Error,bert,1
1189,2/9/2025 6:15,ModernCRM,Service issue caused by email delivery error,Critical Error,bert,1
1359,8/18/2025 15:58,ModernCRM,Email system down due to sending error,Critical Error,bert,1
1414,6/22/2025 23:07,ModernCRM,Email system encountered a sending error,Error,bert,1
1427,10/26/2025 20:25,ModernHR,Email provider had trouble sending emails,Error,bert,1
1453,9/11/2025 1:18,BillingSystem,Mail delivery error impacted email service,Critical Error,bert,1
1554,3/2/2025 9:21,ModernCRM,Email system had a difficulty sending messages,Error,bert,1
1567,5/11/2025 11:17,ThirdPartyAPI,Email system affected by delivery failure,Critical Error,bert,1
1582,9/10/2025 9:27,BillingSystem,Email delivery failure resulted in service issue,Critical Error,bert,1
1860,6/26/2025 1:08,BillingSystem,Email provider experienced a mail delivery issue,Error,bert,1
1867,10/6/2025 11:04,ModernCRM,Email service had a sending malfunction,Error,bert,1
1901,9/22/2025 2:52,ThirdPartyAPI,Email service experienced a mail sending issue,Error,bert,1
1972,3/12/2025 3:48,ThirdPartyAPI,Delivery issue with email service caused outage,Critical Error,bert,1
2049,10/1/2025 22:07,AnalyticsEngine,Email server experienced a delivery problem,Error,bert,1
2165,4/4/2025 16:11,ThirdPartyAPI,Email server had trouble transmitting emails,Error,bert,1
2281,3/23/2025 20:12,ThirdPartyAPI,Mail delivery issue caused service disruption,Critical Error,bert,1
2284,10/4/2025 18:15,BillingSystem,Email service down due to transmission issue,Critical Error,bert,1
2312,3/9/2025 21:16,ModernHR,Email service faced a delivery obstacle,Error,bert,1
2340,3/26/2025 8:10,ModernCRM,Service outage due to email transmission error,Critical Error,bert,1
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,bert,1

In [16]:
pd.set_option('display.max_colwidth', None)
cluster_counts = df['cluster'].value_counts()
large_clusters = cluster_counts[cluster_counts > 10].index
for cluster in large_clusters:
  print(f"Cluster {cluster}:")
  print(df[df['cluster'] == cluster]['log_message'].head(5).to_string(index=False))
  print()

Cluster 0:
           nova.osapi_compute.wsgi.server [req-b9718cd8-f65e-49cc-8349-6cf7122af137 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" status: 200 len: 1893 time: 0.2675118
nova.osapi_compute.wsgi.server [req-4895c258-b2f8-488f-a2a3-4fae63982e48 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" HTTP status code -  200 len: 211 time: 0.0968180
            nova.osapi_compute.wsgi.server [req-ee8bc8ba-9265-4280-9215-dbe000a41209 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" RCODE  200 len: 1874 time: 0.2280791
      nova.osapi_compute.wsgi.server [req-f0bffbc3-5ab0-4916-91c1-0a61dd7d4ec2 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" Return code: 200 len: 1874 time: 0.2131531
            nova.osapi_compute.wsgi.server [req-2bf7cfee-a236-42f3-8fb1-96fefab0b302 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" RCODE  200 len: 1874 time: 0.1794369

Cluster 5:
          nova.compute.claims [req-a07ac654-8e81-416d-bfbb-189116b07969 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: bf8c824d-f099-4433-a41e-e3da7578262e] Total memory: 64172 MB, used: 512.00 MB
     nova.compute.claims [req-d6986b54-3735-4a42-9074-0ba7d9717de9 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: af5f7392-f7d4-4298-b647-c98924c64aa1] memory limit: 96258.00 MB, free: 95746.00 MB
nova.compute.claims [req-72b4858f-049e-49e1-b31e-b562c5018eaf 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 63a0d960-70b6-44c6-b606-491478a5cadf] disk limit not specified, defaulting to unlimited
nova.compute.claims [req-5c8f52bd-8e3c-41f0-95a5-7861d247cafa 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: d96a117b-0193-4549-bdcc-63b917273d1d] vcpu limit not specified, defaulting to unlimited
nova.compute.claims [req-d38f479d-9bb9-4276-9688-52607e8fd350 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 95960536-049b-41f6-9049-05fc479b6a7c] disk limit not specified, defaulting to unlimited

Cluster 11:
User User685 logged out.
 User User395 logged in.
 User User225 logged in.
User User494 logged out.
 User User900 logged in.

Cluster 13:
Backup started at 2025-05-14 07:06:55.
Backup started at 2025-02-15 20:00:19.
  Backup ended at 2025-08-08 13:06:23.
Backup started at 2025-11-14 08:27:43.
Backup started at 2025-12-09 10:19:11.

Cluster 7:
Multiple bad login attempts detected on user 8538 account
    Multiple login failures occurred on user 9052 account
         User 7153 made multiple incorrect login attempts
         User 8300 made multiple incorrect login attempts
      Multiple login failures were detected for user 6373

Cluster 8:
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.

Cluster 21:
System updated to version 3.9.1.
System updated to version 5.5.4.
System updated to version 4.7.4.
System updated to version 3.7.7.
System updated to version 2.6.2.

Cluster 3:
          Shard 6 replication task ended in failure
Data replication task for shard 14 did not complete
          Data replication task failed for shard 17
             Replication of data to shard 14 failed
 Data replication task for shard 6 did not complete

Cluster 4:
File data_6169.csv uploaded successfully by user User953.
File data_3847.csv uploaded successfully by user User175.
File data_7366.csv uploaded successfully by user User282.
File data_1206.csv uploaded successfully by user User359.
File data_1503.csv uploaded successfully by user User151.

Cluster 17:
    Denied access attempt on restricted account Account2682
Unauthorized login attempt on protected account Account5030
            Account Account9437 blocked due to failed login
     Account Account7999 access denied due to login failure
  Invalid login attempt made on secured account Account7864

Cluster 6:
                        Critical system unit error: unit ID Component55
                 System component malfunction: component ID Component79
                Critical system element is down: element ID Component96
                  Essential system part malfunction: part ID Component6
Failure occurred in critical system component: component ID Component92

Cluster 32:
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.

Cluster 16:
System reboot initiated by user User243.
System reboot initiated by user User471.
System reboot initiated by user User216.
System reboot initiated by user User639.
System reboot initiated by user User819.

Cluster 20:
               User 7662 tried to bypass API security measures
      User 2367 failed to provide valid API access credentials
                    User 3569 made an unauthorized API request
         Unauthorized user 2968 tried to access restricted API
User 2186 attempted to access API without proper authorization

Cluster 9:
Account with ID 5351 created by User634.
Account with ID 7813 created by User373.
Account with ID 9827 created by User965.
Account with ID 2520 created by User546.
Account with ID 2300 created by User964.

Cluster 1:
  Email service experiencing issues with sending
        Email server encountered a sending fault
      Mail service encountered a delivery glitch
Service disruption caused by email sending error
       Email system had a problem sending emails

Cluster 10:
  nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=512MB phys_disk=15GB used_disk=0GB total_vcpus=16 used_vcpus=0 pci_stats=[]
nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
                                                                                                                          nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Total usable vcpus: 16, total allocated vcpus: 0
nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]

Cluster 34:
         Abnormal behavior found on server 10, possible security threat
                        Security alert: suspicious activity on server 1
Anomalous activity identified on server 23, security review recommended
     Server 27 experienced potential security incident, review required
     Server 36 experienced potential security incident, review required

Cluster 53:
       Module X experienced an invalid data format issue
              Input format mismatch occurred in module X
   Module X reported an error in input format validation
Module X failed to process input due to formatting error
  Input data format in module X was invalid or corrupted

Cluster 14:
       Detection of multiple disk faults in RAID setup
      RAID array suffered multiple hard drive failures
          RAID array experienced multiple disk crashes
Multiple hard drive issues in RAID configuration found
 Identification of multiple faulty disks in RAID array

Cluster 52:
     Service health check was not successful because of SSL certificate validation failures.
                          Invalid SSL certificate resulted in a failed service health check.
Service health check failure was due to an invalid or improperly configured SSL certificate.
                  An issue with the SSL certificate caused the service health check to fail.
                      Service health check failure was caused by an expired SSL certificate.

Cluster 18:
   Boot process terminated unexpectedly due to kernel issue
System encountered kernel panic during initialization phase
             Boot process was stopped by kernel malfunction
   System encountered kernel failure during bootup sequence
                   Boot sequence failed due to kernel panic

Cluster 42:
User 5127 has escalated admin privileges without authorization
                        User 9745 has escalated to admin level
                 User 8483 escalated privileges to admin level
                        User 1987 has escalated to admin level
                 User 8395 escalated privileges to admin level

Cluster 25:
         System configuration is no longer valid
Configuration is corrupted throughout the system
     Cross-system configuration failure occurred
     System configuration is experiencing errors
        Configuration malfunction is system-wide

Cluster 59:
Potential security threat: Admin privilege escalation for user 5130
                     Admin privilege escalation alert for user 2893
                     Admin privilege escalation alert for user 8532
Potential security threat: Admin privilege escalation for user 1554
        Warning: Potential admin privilege escalation for user 5720

Cluster 26:
          Privilege elevation detected for user 5038
Elevation of admin privileges detected for user 6137
Elevation of admin privileges detected for user 4907
User 6069 has been granted elevated admin privileges
     Admin privilege elevation warning for user 7574

In [26]:
import re

def classify_with_regex(log_messages):
  regex_patterns = {
      r"nova\.osapi_compute\.wsgi\.server.*GET \/v2\/[a-f0-9\-]+\/servers\/detail HTTP\/1\.1.*(status|HTTP status code|RCODE|Return code):?\s*200.*time:\s*[0-9\.]+": "HTTP Status",
      r"nova\.compute\.claims.*(Total memory|memory limit|disk limit|vcpu limit).*": "Resource Usage",
      r"User\s+\w+\s+logged\s+(in|out)\.": "User Action",
      r"Backup (started|ended) at .*": "System Notification",
      r".*(Multiple|multiple).*(login|incorrect).*(attempts|failures).*": "Security Alert",
      r"Backup completed successfully\.": "System Notification",
      r"System updated to version \d+\.\d+\.\d+\.": "System Notification",
      r".*(replication|Replication).*(failed|failure|did not complete).*": "Error",
      r"File .* uploaded successfully by user .*": "System Notification",
      r".*(Denied access|Unauthorized login|blocked|Invalid login attempt).*": "Security Alert",
      r".*(Critical system|malfunction|Failure occurred).*component.*ID .*": "Critical Error",
      r"Disk cleanup completed successfully\.": "System Notification",
      r"System reboot initiated by user .*": "System Notification",
      r"User \d+.*(unauthorized|failed to provide valid API|bypass API|without proper authorization).*": "Security Alert",
      r"Account with ID .* created by .*": "User Action",
      r".*(Email|Mail).*(issue|error|fault|glitch|problem).*": "Error",
      r"nova\.compute\.resource_tracker.*(Final resource view|Total usable vcpus).*": "Resource Usage",
      r".*(security threat|suspicious activity|potential security incident|Anomalous activity).*": "Security Alert",
      r".*(invalid data format|format mismatch|input format|format validation).*": "Data Error",
      r".*(RAID|disk).*(failure|fault|crash|faulty).*": "Hardware Failure",
      r".*SSL certificate.*(failed|invalid|expired|validation).*": "Security Alert",
      r".*(kernel panic|kernel failure|boot process|boot sequence).*(failed|terminated|stopped).*": "Critical Error",
      r"User \d+.*escalated.*admin.*": "Security Alert",
      r".*configuration.*(invalid|corrupted|failure|error).*": "Error",
      r".*(admin privilege escalation|Potential security threat).*": "Security Alert",
      r".*(privilege elevation|elevated admin privileges).*": "Security Alert"
  }
  for pattern, label in regex_patterns.items():
    if re.search(pattern, log_messages, re.IGNORECASE):
      return label
  return None

In [27]:
classify_with_regex("User user1234 logged OUT.")

'User Action'

In [28]:
df['regex_label'] = df['log_message'].apply(classify_with_regex)

In [29]:
df

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,"nova.osapi_compute.wsgi.server [req-b9718cd8-f65e-49cc-8349-6cf7122af137 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 ""GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1"" status: 200 len: 1893 time: 0.2675118",HTTP Status,bert,0,HTTP Status
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1,Error
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2,None
3,2025-07-12 00:24:16,ModernHR,"nova.osapi_compute.wsgi.server [req-4895c258-b2f8-488f-a2a3-4fae63982e48 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 ""GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1"" HTTP status code - 200 len: 211 time: 0.0968180",HTTP Status,bert,0,None
4,2025-06-02 18:25:23,BillingSystem,"nova.osapi_compute.wsgi.server [req-ee8bc8ba-9265-4280-9215-dbe000a41209 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 ""GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1"" RCODE 200 len: 1874 time: 0.2280791",HTTP Status,bert,0,HTTP Status
...,...,...,...,...,...,...,...
2405,2025-08-13 07:29:25,ModernHR,"nova.osapi_compute.wsgi.server [req-96c3ec98-21a0-4af2-84a8-d4989512413e 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 ""GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1"" Return code: 200 len: 1916 time: 0.2677610",HTTP Status,bert,0,HTTP Status
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed logins,Security Alert,bert,7,None
2407,2025-08-03 03:07:47,ThirdPartyAPI,"nova.metadata.wsgi.server [req-b6d4a270-accb-4c3a-8179-9611e52e1768 - - - - -] 10.11.21.124,10.11.10.1 ""GET /openstack/2013-10-17 HTTP/1.1"" RCODE 200 len: 157 time: 0.2249990",HTTP Status,bert,0,None
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,bert,1,None
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for user ID 8555,Security Alert,bert,7,None

In [32]:
df[df.regex_label.notnull()]

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,"nova.osapi_compute.wsgi.server [req-b9718cd8-f65e-49cc-8349-6cf7122af137 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 ""GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1"" status: 200 len: 1893 time: 0.2675118",HTTP Status,bert,0,HTTP Status
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1,Error
4,2025-06-02 18:25:23,BillingSystem,"nova.osapi_compute.wsgi.server [req-ee8bc8ba-9265-4280-9215-dbe000a41209 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 ""GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1"" RCODE 200 len: 1874 time: 0.2280791",HTTP Status,bert,0,HTTP Status
5,2025-10-09 10:30:31,ModernHR,"nova.osapi_compute.wsgi.server [req-f0bffbc3-5ab0-4916-91c1-0a61dd7d4ec2 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 ""GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1"" Return code: 200 len: 1874 time: 0.2131531",HTTP Status,bert,0,HTTP Status
6,3/1/2025 19:14,ModernHR,Shard 6 replication task ended in failure,Error,bert,3,Error
...,...,...,...,...,...,...,...
2400,2025-01-07 09:13:28,ThirdPartyAPI,"nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Total usable vcpus: 16, total allocated vcpus: 1",Resource Usage,bert,10,Resource Usage
2401,2025-12-05 15:51:51,ModernCRM,"nova.osapi_compute.wsgi.server [req-4bdf00b0-3bbc-44fa-bd84-de85ec43c8a2 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 ""GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1"" status: 200 len: 1916 time: 0.2769570",HTTP Status,bert,0,HTTP Status
2403,10/1/2025 1:31,ModernCRM,Backup completed successfully.,System Notification,regex,8,System Notification
2404,2025-09-18 02:18:30,ThirdPartyAPI,"nova.osapi_compute.wsgi.server [req-2c9c783f-3c7a-4844-87b1-e207a38c74ab 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 ""GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1"" Return code: 200 len: 1893 time: 0.2527661",HTTP Status,bert,0,HTTP Status
2405,2025-08-13 07:29:25,ModernHR,"nova.osapi_compute.wsgi.server [req-96c3ec98-21a0-4af2-84a8-d4989512413e 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 ""GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1"" Return code: 200 len: 1916 time: 0.2677610",HTTP Status,bert,0,HTTP Status

In [33]:
df_non_regex = df[df.regex_label.isnull()].copy()
df_non_regex.shape

(1141, 7)

In [34]:
print(df_non_regex['target_label'].value_counts()[df_non_regex['target_label'].value_counts() <=5].index.tolist())

['Workflow Error', 'Deprecation Warning']

In [38]:
df_non_legacy = df_non_regex[df_non_regex['source']!='LegacyCRM']
df_non_legacy.source.unique()

array(['AnalyticsEngine', 'ModernHR', 'BillingSystem', 'ThirdPartyAPI',
       'ModernCRM'], dtype=object)

In [40]:
log_messages = df_non_legacy['log_message'].astype(str).tolist()
print(f"Generating embeddings for df_non_legacy {len(log_messages)} log messages...")
filtered_embeddings = model.encode(log_messages, show_progress_bar=True, batch_size=32)
print(f"Embedding shape: {filtered_embeddings.shape}")
print()

Generating embeddings for df_non_legacy 1134 log messages...

Batches:   0%|          | 0/36 [00:00<?, ?it/s]

Embedding shape: (1134, 384)

In [42]:
X = filtered_embeddings
y = df_non_legacy['target_label']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
clf = LogisticRegression(max_iter=1000)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
report = classification_report(y_test, y_pred)
print(report)

                precision    recall  f1-score   support

Critical Error       1.00      0.95      0.98        42
         Error       0.95      1.00      0.97        39
   HTTP Status       1.00      1.00      1.00       180
Resource Usage       1.00      1.00      1.00        20
Security Alert       1.00      1.00      1.00        60

      accuracy                           0.99       341
     macro avg       0.99      0.99      0.99       341
  weighted avg       0.99      0.99      0.99       341

In [44]:
import joblib
import os

# Create the directory if it doesn't exist
if not os.path.exists('models'):
    os.makedirs('models')

joblib.dump(clf, 'models/jobclassifier.joblib')

['models/jobclassifier.joblib']

In [71]:
# First, let's create a dummy .py file to test
with open('bert_processor.py', 'r') as f:
    print('bert_processor.py read successfully.')
    !python bert_processor.py

bert_processor.py created successfully.
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100% 103/103 [00:00<00:00, 1176.21it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
alpha.osapi_compute.wsgi.server - 12.10.11.1 - API returned 404 not found error -> HTTP Status
GET /v2/3454/servers/detail HTTP/1.1 RCODE 404 len: 1583 time: 0.1878400 -> HTTP Status
System crashed due to drivers errors when restarting the server -> Critical Error
Hey bro, chill ya! -> Unclassified
Multiple login failures occurred on user 6454 account -> Security Alert
Server A790 was restarted unexpectedly during the process of data transfer -> Error

In [90]:
with open('llm_processor.py', 'r') as f:
    print('llm_processor.py read successfully.')
    !python llm_processor.py

llm_processor.py read successfully.
Workflow Error
Deprecation Warning
Unclassified

In [101]:
import llm_processor
import bert_processor

def classify(logs):
  Labels = []
  for source, log_msg in logs:
    Label = classify_log(source, log_msg)
    Labels.append(Label)
  return Labels

def classify_log(source, log_message):
  if source == "LegacyCRM":
    # Using the imported module instead of opening the file as text
    return llm_processor.classify_with_llm(log_message)
  else:
    label = classify_with_regex(log_message)
    if label is None:
      return bert_processor.classify_with_bert(log_message)

    return label

In [111]:
def classify_csv(input_file):
    import pandas as pd
    df = pd.read_csv(input_file)

    # Perform classification
    df["target_label"] = classify(list(zip(df["source"], df["log_message"])))

    # Save the modified file
    output_file = "resources/output.csv"
    df.to_csv(output_file, index=False)

    return output_file

In [112]:
if __name__ == '__main__':
    # This function already reads the CSV and runs classification
    output_path = classify_csv("test.csv")

    print(f"Classification complete. Results saved to: {output_path}")

    # Test with the manual list
    logs = [
        ("ModernCRM", "IP 192.168.133.114 blocked due to potential attack"),
        ("BillingSystem", "User 12345 logged in."),
        ("AnalyticsEngine", "File data_6957.csv uploaded successfully by user User265."),
        ("AnalyticsEngine", "Backup completed successfully."),
        ("ModernHR", "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1 RCODE  200 len: 1583 time: 0.1878400"),
        ("ModernHR", "Admin access escalation detected for user 9429"),
        ("LegacyCRM", "Case escalation for ticket ID 7324 failed because the assigned support agent is no longer active."),
        ("LegacyCRM", "Invoice generation process aborted for order ID 8910 due to invalid tax calculation module."),
        ("LegacyCRM", "The 'BulkEmailSender' feature is no longer supported. Use 'EmailCampaignManager' for improved functionality."),
        ("LegacyCRM", " The 'ReportGenerator' module will be retired in version 4.0. Please migrate to the 'AdvancedAnalyticsSuite' by Dec 2025")
    ]

    labels = classify(logs)

    print("\n--- Manual Logs Classification Results ---")
    for log, label in zip(logs, labels):
        print(f"{log[0]} -> {label}")

    # To see the CSV results, we should read the output file
    print("\n--- CSV Logs Classification Results (First 5) ---")
    import pandas as pd
    print(pd.read_csv(output_path)[['source', 'target_label']])

Classification complete. Results saved to: resources/output.csv

--- Manual Logs Classification Results ---
ModernCRM -> Security Alert
BillingSystem -> User Action
AnalyticsEngine -> System Notification
AnalyticsEngine -> System Notification
ModernHR -> HTTP Status
ModernHR -> Security Alert
LegacyCRM -> Workflow Error
LegacyCRM -> Workflow Error
LegacyCRM -> Deprecation Warning
LegacyCRM -> Deprecation Warning

--- CSV Logs Classification Results (First 5) ---
            source         target_label
0        ModernCRM       Security Alert
1    BillingSystem          User Action
2  AnalyticsEngine  System Notification
3  AnalyticsEngine  System Notification
4         ModernHR          HTTP Status
5         ModernHR       Security Alert
6        LegacyCRM       Workflow Error
7        LegacyCRM       Workflow Error
8        LegacyCRM  Deprecation Warning
9        LegacyCRM  Deprecation Warning

In [73]:
!pip install groq

Collecting groq
  Downloading groq-1.1.2-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from groq) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from groq) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.14 in /usr/local/lib/python3.12/dist-packages (from groq) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->groq) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.4.2)
Downloading groq-1.1.2-py3-none-any.whl (141 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.7/141.7 kB 4.5 MB/s eta 0:00:00
Installing collected packages: groq
Successfully installed groq-1.1.2